# 应用服务 WEB 访问端口
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Aa123456
